# File contents of "ios/Podfile"
platform :ios, '9.0'

target 'compoteTestRN' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    # the following ones are the ones taken from "Libraries" in Xcode:
    'RCTAnimation',
    'RCTActionSheet',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # the following dependencies are dependencies of React native itself.
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'

  # your other libraries will follow here!
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'TouchID', :path => '../node_modules/react-native-touch-id'
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/AdMob', '~> 6.2.0'
  pod 'Firebase/Analytics'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end

# The following is needed to ensure the "archive" step works in XCode.
# It removes React from the Pods project, as it is already included in the main project.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
